import type { Center, MenuItem } from "./types";

/** Shorthand for menu items. */
const m = (name: string, ...allergens: MenuItem["allergens"]): MenuItem => ({ name, allergens });

export const pinonGrove: Center = {
  id: "pinon-grove",
  name: "Piñon Grove Early Learning",
  shortName: "Piñon Grove",
  city: "Albuquerque",
  state: "NM",
  timeZone: "America/Denver",
  address: "4120 Piñon Grove Lane NE, Albuquerque, NM 87111",
  phone: "505-555-0142",
  email: "hello@pinongrove.example",
  languages: ["en", "es"],
  hours: { open: "07:00", close: "18:00", days: "Monday to Friday" },
  officeHours: { start: "07:30", end: "17:30", typicalReplyMinutes: 120 },
  meals: "provided",
  staff: [
    { id: "elena-vigil", name: "Elena Vigil", role: "director", title: "Director and owner" },
    { id: "marcus-benally", name: "Marcus Benally", role: "assistant_director", title: "Assistant director and enrollment" },
    { id: "grace-lucero", name: "Grace Lucero", role: "lead_teacher", title: "Lead teacher, Hummingbirds", roomId: "hummingbirds" },
    { id: "tomas-archuleta", name: "Tomás Archuleta", role: "lead_teacher", title: "Lead teacher, Jackrabbits", roomId: "jackrabbits" },
    { id: "kim-nguyen", name: "Kim Nguyen", role: "lead_teacher", title: "Lead teacher, Roadrunners", roomId: "roadrunners" },
    { id: "daniel-ortiz", name: "Daniel Ortiz", role: "lead_teacher", title: "Lead teacher, Coyotes", roomId: "coyotes" },
    { id: "lucia-sandoval", name: "Lucía Sandoval", role: "lead_teacher", title: "Lead teacher, Sunflowers", roomId: "sunflowers" },
  ],
  rooms: [
    { id: "hummingbirds", name: "Hummingbirds", program: "infant", ages: "6 weeks to 12 months", ratio: "1 to 4", leadTeacherId: "grace-lucero", tuitionMonthly: 950, waitlist: "about 3 to 4 months" },
    { id: "jackrabbits", name: "Jackrabbits", program: "toddler", ages: "12 to 24 months", ratio: "1 to 5", leadTeacherId: "tomas-archuleta", tuitionMonthly: 900, waitlist: "about 1 to 2 months" },
    { id: "roadrunners", name: "Roadrunners", program: "twos", ages: "2 years", ratio: "1 to 7", leadTeacherId: "kim-nguyen", tuitionMonthly: 850, waitlist: "about 1 to 2 months" },
    { id: "coyotes", name: "Coyotes", program: "preschool", ages: "3 years", ratio: "1 to 10", leadTeacherId: "daniel-ortiz", tuitionMonthly: 800, waitlist: "about 1 to 2 months" },
    { id: "sunflowers", name: "Sunflowers (NM Pre-K)", program: "prek", ages: "4 to 5 years", ratio: "1 to 10", leadTeacherId: "lucia-sandoval", tuitionMonthly: 775, waitlist: "about 1 to 2 months" },
  ],
  fees: {
    registration: 75,
    registrationNote: "Once per year for families paying tuition directly. Not charged to Child Care Assistance families.",
    waitlistFee: null,
    siblingDiscountPct: null,
    latePickupPerMinute: null,
    backupLunch: null,
  },
  assistance: {
    name: "New Mexico Child Care Assistance",
    summary:
      "Pays the full cost of care at participating providers for families where every available parent works, looks for work, or attends school, regardless of income. Eligibility is decided by the state ECECD. Copays are currently $0 and may return under certain economic conditions. Piñon Grove participates and charges assistance families no add-on fees.",
  },
  closures: [
    { date: "2026-09-07", name: "Labor Day", kind: "holiday" },
    { date: "2026-11-26", endDate: "2026-11-27", name: "Thanksgiving break", kind: "holiday" },
    { date: "2026-12-24", endDate: "2027-01-01", name: "Winter break", kind: "break" },
    { date: "2027-01-18", name: "Martin Luther King Jr. Day", kind: "holiday" },
    { date: "2027-03-12", name: "Staff training day", kind: "training" },
    { date: "2027-05-31", name: "Memorial Day", kind: "holiday" },
    { date: "2027-07-05", name: "Independence Day, observed", kind: "holiday" },
    { date: "2027-09-06", name: "Labor Day", kind: "holiday" },
  ],
  events: [
    { date: "2026-10-03", endDate: "2026-10-11", name: "Balloon Fiesta week", note: "Open regular hours. Arrival by 9:30 am is fine for families at early launches." },
    { date: "2026-10-12", name: "Indigenous Peoples' Day", note: "Open regular hours, with classroom activities." },
    { date: "2026-10-22", endDate: "2026-10-23", name: "Fall parent-teacher conferences", note: "Open regular hours. Sign up for a time in the app." },
    { date: "2026-10-28", endDate: "2026-11-02", name: "Día de los Muertos ofrenda", note: "Open regular hours. Families are invited to add photos to the lobby ofrenda." },
    { date: "2026-11-11", name: "Veterans Day", note: "Open regular hours." },
    { date: "2027-02-15", name: "Presidents Day", note: "Open regular hours." },
    { date: "2027-04-15", endDate: "2027-04-16", name: "Spring parent-teacher conferences", note: "Open regular hours. Sign up for a time in the app." },
    { date: "2027-06-18", name: "Juneteenth, observed", note: "Open regular hours." },
  ],
  menu: {
    cycleStart: "2026-08-31",
    infantNote:
      "Hummingbirds infants follow their own feeding plans. The center provides iron-fortified formula and baby food, and families may bring labeled breast milk.",
    weeks: [
      [
        { breakfast: m("Whole-grain cereal, bananas and milk", "wheat", "dairy"), lunch: m("Green chile mac and cheese, apple slices and milk", "wheat", "dairy"), pmSnack: m("Cucumber slices and hummus", "sesame") },
        { breakfast: m("Scrambled eggs, tortilla and orange slices", "egg", "wheat"), lunch: m("Chicken calabacitas with rice, pinto beans and milk", "dairy"), pmSnack: m("Yogurt and berries", "dairy") },
        { breakfast: m("Oatmeal with cinnamon, pears and milk", "dairy"), lunch: m("Turkey and cheese quesadillas, black beans, salsa and milk", "wheat", "dairy"), pmSnack: m("Apple slices and cheese", "dairy") },
        { breakfast: m("Blueberry muffin and milk", "wheat", "egg", "dairy"), lunch: m("Beef and bean burritos with red chile, corn and milk", "wheat", "dairy"), pmSnack: m("Whole-grain crackers and sunflower seed butter", "wheat") },
        { breakfast: m("Whole-wheat pancakes, strawberries and milk", "wheat", "egg", "dairy"), lunch: m("Baked fish tacos on corn tortillas, cabbage slaw and milk", "fish", "dairy"), pmSnack: m("Carrot sticks and ranch dip", "dairy", "egg") },
      ],
      [
        { breakfast: m("Egg and potato breakfast burrito", "egg", "wheat"), lunch: m("Spaghetti with meat sauce, green beans and milk", "wheat", "dairy"), pmSnack: m("Orange slices and a cheese stick", "dairy") },
        { breakfast: m("Yogurt parfait with granola", "dairy", "wheat"), lunch: m("Pork and hominy posole, tortilla and milk", "wheat", "dairy"), pmSnack: m("Rice cakes and apple butter") },
        { breakfast: m("Cheese toast and melon", "wheat", "dairy"), lunch: m("Green chile chicken enchiladas on corn tortillas, Spanish rice and milk", "dairy"), pmSnack: m("Hummus and pita", "sesame", "wheat") },
        { breakfast: m("Oatmeal with raisins and milk", "dairy"), lunch: m("Turkey meatballs, mashed potatoes, peas and milk", "egg", "wheat", "dairy"), pmSnack: m("Pear slices and yogurt", "dairy") },
        { breakfast: m("French toast sticks and milk", "wheat", "egg", "dairy"), lunch: m("Bean and cheese tostadas, lettuce and milk", "dairy"), pmSnack: m("A small biscochito and milk", "wheat", "egg", "dairy") },
      ],
    ],
  },
  tours: [
    { weekday: 2, time: "09:30" },
    { weekday: 2, time: "16:00" },
    { weekday: 4, time: "09:30" },
    { weekday: 4, time: "16:00" },
  ],
  tourMinutes: 30,
  illness: {
    feverThresholdF: 100.4,
    feverRequiresOtherSymptoms: false,
    feverFreeHoursToReturn: 24,
    vomitDiarrheaHoursToReturn: 24,
    antibioticHoursToReturn: 24,
  },
  announcements: [
    {
      id: "pg-fiesta-2026",
      postedAt: "2026-09-28T15:00:00Z",
      postedBy: "Elena Vigil",
      title: "Balloon Fiesta week",
      body: "We're open regular hours October 3 to 11. If you're at a morning launch, arriving by 9:30 am is fine. We'll watch for balloons from the play yard!",
      showFrom: "2026-10-01",
      showUntil: "2026-10-11",
    },
    {
      id: "pg-ofrenda-2026",
      postedAt: "2026-10-05T15:00:00Z",
      postedBy: "Elena Vigil",
      title: "Lobby ofrenda for Día de los Muertos",
      body: "From October 28 to November 2, families are invited to add photos of loved ones to our lobby ofrenda.",
      showFrom: "2026-10-05",
      showUntil: "2026-11-02",
    },
  ],
  tableUpdates: {
    calendar: { updatedAt: "2026-08-03", updatedBy: "Elena Vigil" },
    menu: { updatedAt: "2026-08-24", updatedBy: "Elena Vigil" },
    tuition: { updatedAt: "2026-03-20", updatedBy: "Elena Vigil" },
    tours: { updatedAt: "2026-08-03", updatedBy: "Marcus Benally" },
    hours: { updatedAt: "2026-08-03", updatedBy: "Elena Vigil" },
  },
  savedAnswers: [
    {
      id: "pg-sa-parking",
      question: "Where should I park at drop-off?",
      answer: "Please use the 10-minute spots along the front of the building. The fire lane by the front door must stay clear.",
      savedBy: "Elena Vigil",
      savedAt: "2026-09-15T16:20:00Z",
      keywords: ["parking", "park", "drop-off spot", "estacionar"],
    },
    {
      id: "pg-sa-fiesta-trip",
      question: "Does the center take children to Balloon Fiesta?",
      answer: "No. Because of the crowds and early hours, we don't take field trips to Balloon Fiesta. Children watch for balloons from the play yard most mornings that week.",
      savedBy: "Elena Vigil",
      savedAt: "2026-09-30T14:05:00Z",
      keywords: ["balloon fiesta", "field trip", "fiesta"],
    },
  ],
};

export const quailRidge: Center = {
  id: "quail-ridge",
  name: "Quail Ridge Early Learning",
  shortName: "Quail Ridge",
  city: "Seattle",
  state: "WA",
  timeZone: "America/Los_Angeles",
  address: "2210 NE Quail Ridge Way, Seattle, WA 98115",
  phone: "206-555-0187",
  email: "hello@quailridge.example",
  languages: ["en", "zh"],
  hours: { open: "07:30", close: "18:00", days: "Monday to Friday" },
  officeHours: { start: "08:00", end: "17:30", typicalReplyMinutes: 120 },
  meals: "pack_lunch",
  staff: [
    { id: "hannah-lindqvist", name: "Hannah Lindqvist", role: "director", title: "Director and owner" },
    { id: "jamal-wright", name: "Jamal Wright", role: "assistant_director", title: "Assistant director and enrollment" },
    { id: "sofia-reyes", name: "Sofia Reyes", role: "lead_teacher", title: "Lead teacher, Otters", roomId: "otters" },
    { id: "ben-tanaka", name: "Ben Tanaka", role: "lead_teacher", title: "Lead teacher, Chickadees", roomId: "chickadees" },
    { id: "marisol-ortega", name: "Marisol Ortega", role: "lead_teacher", title: "Lead teacher, Ferns", roomId: "ferns" },
    { id: "grace-liu", name: "Grace Liu", role: "lead_teacher", title: "Lead teacher, Orcas", roomId: "orcas" },
  ],
  rooms: [
    { id: "otters", name: "Otters", program: "infant", ages: "6 weeks to 12 months", ratio: "1 to 4", leadTeacherId: "sofia-reyes", tuitionMonthly: 2600, waitlist: "about 12 months" },
    { id: "chickadees", name: "Chickadees", program: "toddler", ages: "12 to 30 months", ratio: "1 to 7", leadTeacherId: "ben-tanaka", tuitionMonthly: 2350, waitlist: "about 6 months" },
    { id: "ferns", name: "Ferns", program: "preschool", ages: "30 months to 4 years", ratio: "1 to 10", leadTeacherId: "marisol-ortega", tuitionMonthly: 2050, partTimeMonthly: 1450, partTimeSchedule: "Monday, Wednesday and Friday", waitlist: "about 2 to 3 months" },
    { id: "orcas", name: "Orcas (Pre-K)", program: "prek", ages: "4 to 5 years", ratio: "1 to 10", leadTeacherId: "grace-liu", tuitionMonthly: 1950, partTimeMonthly: 1375, partTimeSchedule: "Monday, Wednesday and Friday", waitlist: "about 2 to 3 months" },
  ],
  fees: {
    registration: 150,
    registrationNote: "Per child, once a year.",
    waitlistFee: 100,
    siblingDiscountPct: 10,
    latePickupPerMinute: 1,
    backupLunch: 8,
  },
  assistance: {
    name: "Working Connections Child Care",
    summary:
      "Washington's child care subsidy. DCYF decides eligibility and sets each family's copayment. Quail Ridge accepts it, and Jamal explains how a family's copayment works with tuition.",
  },
  closures: [
    { date: "2026-09-07", name: "Labor Day", kind: "holiday" },
    { date: "2026-11-11", name: "Veterans Day", kind: "holiday" },
    { date: "2026-11-26", endDate: "2026-11-27", name: "Thanksgiving and Native American Heritage Day", kind: "holiday" },
    { date: "2026-12-24", endDate: "2027-01-01", name: "Winter break", kind: "break" },
    { date: "2027-01-18", name: "Martin Luther King Jr. Day", kind: "holiday" },
    { date: "2027-01-29", name: "Staff training day", kind: "training" },
    { date: "2027-02-15", name: "Presidents Day", kind: "holiday" },
    { date: "2027-05-28", name: "Staff training day", kind: "training" },
    { date: "2027-05-31", name: "Memorial Day", kind: "holiday" },
    { date: "2027-06-18", name: "Juneteenth, observed", kind: "holiday" },
    { date: "2027-07-05", name: "Independence Day, observed", kind: "holiday" },
    { date: "2027-09-06", name: "Labor Day", kind: "holiday" },
  ],
  events: [
    { date: "2026-10-12", name: "Indigenous Peoples' Day", note: "Open regular hours, with classroom activities." },
    { date: "2026-10-15", name: "Picture day", note: "Open regular hours. Photos are taken in the morning." },
    { date: "2026-11-16", endDate: "2026-11-20", name: "Fall conferences", note: "Open regular hours. Sign up for a time in the app." },
    { date: "2027-02-05", name: "Lunar New Year celebration", note: "Open regular hours. Families are welcome to share traditions with the class." },
    { date: "2027-05-17", endDate: "2027-05-21", name: "Spring conferences", note: "Open regular hours. Sign up for a time in the app." },
  ],
  menu: {
    cycleStart: "2026-08-31",
    infantNote: "For Otters infants, families provide formula or labeled breast milk and baby food.",
    weeks: [
      [
        { amSnack: m("Apple slices and cheddar", "dairy"), pmSnack: m("Whole-grain crackers and hummus", "wheat", "sesame"), backupLunch: { main: m("Turkey and cheese sandwich", "wheat", "dairy"), alternative: m("Sunflower seed butter and jam sandwich", "wheat") } },
        { amSnack: m("Banana and an oat bar", "wheat"), pmSnack: m("Yogurt with blueberries", "dairy"), backupLunch: { main: m("Cheese quesadilla", "wheat", "dairy"), alternative: m("Black bean and rice bowl") } },
        { amSnack: m("Pear slices and rice cakes"), pmSnack: m("Cheese stick and halved grapes", "dairy"), backupLunch: { main: m("Pasta with marinara and parmesan", "wheat", "dairy"), alternative: m("Pasta with marinara, no cheese", "wheat") } },
        { amSnack: m("Whole-grain toast with sunflower seed butter", "wheat"), pmSnack: m("Carrot sticks and hummus", "sesame"), backupLunch: { main: m("Chicken teriyaki with rice", "soy", "wheat"), alternative: m("Chicken with rice and steamed broccoli") } },
        { amSnack: m("Mini blueberry muffin", "wheat", "egg", "dairy"), pmSnack: m("Edamame and orange slices", "soy"), backupLunch: { main: m("Hummus and veggie wrap", "wheat", "sesame"), alternative: m("Turkey roll-ups with cucumber") } },
      ],
    ],
  },
  tours: [
    { weekday: 3, time: "10:00" },
    { weekday: 5, time: "15:30" },
  ],
  tourMinutes: 30,
  illness: {
    feverThresholdF: 101,
    youngInfantThresholdF: 100.4,
    feverRequiresOtherSymptoms: true,
    feverFreeHoursToReturn: 24,
    vomitDiarrheaHoursToReturn: 24,
  },
  announcements: [
    {
      id: "qr-raingear-2026",
      postedAt: "2026-10-01T16:00:00Z",
      postedBy: "Hannah Lindqvist",
      title: "Rain gear check",
      body: "The wet season is here. Please check that your child's rain suit and boots still fit, and label both.",
      showFrom: "2026-10-01",
      showUntil: "2026-10-31",
    },
    {
      id: "qr-picture-day-2026",
      postedAt: "2026-10-02T16:00:00Z",
      postedBy: "Jamal Wright",
      title: "Picture day is Thursday, October 15",
      body: "Photos are taken in the morning. Order forms are in the app.",
      showFrom: "2026-10-02",
      showUntil: "2026-10-15",
    },
  ],
  tableUpdates: {
    calendar: { updatedAt: "2026-08-10", updatedBy: "Hannah Lindqvist" },
    menu: { updatedAt: "2026-08-26", updatedBy: "Hannah Lindqvist" },
    tuition: { updatedAt: "2026-08-10", updatedBy: "Jamal Wright" },
    tours: { updatedAt: "2026-09-01", updatedBy: "Jamal Wright" },
    hours: { updatedAt: "2026-08-10", updatedBy: "Hannah Lindqvist" },
  },
  savedAnswers: [
    {
      id: "qr-sa-parking",
      question: "Where should I park at pickup?",
      answer: "Use the four 15-minute spots in our lot, or street parking on NE 75th. Please don't block the neighbors' driveways.",
      savedBy: "Hannah Lindqvist",
      savedAt: "2026-09-10T22:10:00Z",
      keywords: ["parking", "park", "pickup spot", "停车"],
    },
    {
      id: "qr-sa-cloth-diapers",
      question: "Can we use cloth diapers?",
      answer: "Yes. Send cloth diapers with covers and a labeled wet bag, and we'll send soiled diapers home each day.",
      savedBy: "Hannah Lindqvist",
      savedAt: "2026-09-22T19:40:00Z",
      keywords: ["cloth diaper", "reusable diaper", "diapers"],
    },
  ],
};

export const centers = [pinonGrove, quailRidge];
