// Converts src/content/handbooks/*.md into a TypeScript module of raw strings,
// so handbooks stay readable Markdown but bundle reliably on Vercel.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";

const dir = join(process.cwd(), "src/content/handbooks");
const files = readdirSync(dir).filter((f) => f.endsWith(".md")).sort();
const entries = files.map((f) => `  ${JSON.stringify(basename(f, ".md"))}: ${JSON.stringify(readFileSync(join(dir, f), "utf8"))},`);
const out = `// Generated by scripts/build-content.mjs. Do not edit; edit the .md files instead.
export const handbookMarkdown: Record<string, string> = {
${entries.join("\n")}
};
`;
writeFileSync(join(dir, "index.generated.ts"), out);
console.log(`build-content: ${files.length} handbooks`);
